# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\x12\x05image\"\'\n\x16ImageClassifierRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x88\x01\n\x17ImageClassifierResponse\x12\x38\n\x05state\x18\x01 \x01(\x0e\x32$.image.ImageClassifierResponse.StateH\x00\x88\x01\x01\x12\r\n\x05\x63lass\x18\x02 \x01(\x03\"\x1a\n\x05State\x12\t\n\x05\x45rror\x10\x00\x12\x06\n\x02Ok\x10\x01\x42\x08\n\x06_state2a\n\rImageClassify\x12P\n\rClassifyImage\x12\x1d.image.ImageClassifierRequest\x1a\x1e.image.ImageClassifierResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_IMAGECLASSIFIERREQUEST']._serialized_start=22
  _globals['_IMAGECLASSIFIERREQUEST']._serialized_end=61
  _globals['_IMAGECLASSIFIERRESPONSE']._serialized_start=64
  _globals['_IMAGECLASSIFIERRESPONSE']._serialized_end=200
  _globals['_IMAGECLASSIFIERRESPONSE_STATE']._serialized_start=164
  _globals['_IMAGECLASSIFIERRESPONSE_STATE']._serialized_end=190
  _globals['_IMAGECLASSIFY']._serialized_start=202
  _globals['_IMAGECLASSIFY']._serialized_end=299
# @@protoc_insertion_point(module_scope)
