# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_pb2 as image__pb2


class ImageClassifyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyImage = channel.unary_unary(
                '/image.ImageClassify/ClassifyImage',
                request_serializer=image__pb2.ImageClassifierRequest.SerializeToString,
                response_deserializer=image__pb2.ImageClassifierResponse.FromString,
                )


class ImageClassifyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClassifyImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageClassifyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyImage,
                    request_deserializer=image__pb2.ImageClassifierRequest.FromString,
                    response_serializer=image__pb2.ImageClassifierResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'image.ImageClassify', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageClassify(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClassifyImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/image.ImageClassify/ClassifyImage',
            image__pb2.ImageClassifierRequest.SerializeToString,
            image__pb2.ImageClassifierResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
